[general]
show_welcome = false
skip_boot_anim = true

[sys]
mem_limit = '128'

[sys.files]
flashrom_path = '/work/artifacts/optimization/final-release-v1/flash.bin'
eeprom_path = '/home/ubuntu/.local/share/xemu/xemu/eeprom.bin'
hdd_path = '/work/artifacts/optimization/xiso-release-v1/private-hdd.qcow2'
dvd_path = '/suite.iso'

