[general]
show_welcome = false
skip_boot_anim = true

[sys]
mem_limit = '128'

[sys.files]
flashrom_path = '/work/bios/clean-room-xemu/SpiritBoot-release.bin'
eeprom_path = '/home/ubuntu/.local/share/xemu/xemu/eeprom.bin'
hdd_path = '/seed.qcow2'
dvd_path = '/work/artifacts/optimization/guests/benchmark-smoke.iso'

