XBE_TITLE = clean-room-contracts
GEN_XISO = $(XBE_TITLE).iso
NXDK_DIR ?= /usr/src/nxdk
SRCS = $(CURDIR)/main.c $(CURDIR)/pending.c $(CURDIR)/../api-regression/tap.c $(CURDIR)/../api-regression/io/scatter.c
include $(NXDK_DIR)/Makefile
