[general]
show_welcome = false
skip_boot_anim = true

[sys]
mem_limit = '128'

[sys.files]
flashrom_path = '/work/artifacts/clean-room/final-debug-v2/flash.bin'
eeprom_path = '/home/ubuntu/.local/share/xemu/xemu/eeprom.bin'
hdd_path = '/seed.qcow2'
dvd_path = '/work/artifacts/clean-room/guests/final-contracts.iso'

